stages:
  ingest:
    cmd: ./venv311/bin/python src/pipeline/ingestion.py
    deps:
      - src/pipeline/ingestion.py
      - params.yaml
    outs:
      - data/raw/Bank_churn.csv

  preprocess:
    cmd: ./venv311/bin/python src/pipeline/pre_processing.py
    deps:
      - src/pipeline/pre_processing.py
      - data/raw/Bank_churn.csv
      - params.yaml
    outs:
      - data/processed/bank_churn_processed.csv

  feature_engineering:
    cmd: ./venv311/bin/python src/pipeline/feature_engineering.py
    deps:
      - src/pipeline/feature_engineering.py
      - data/processed/bank_churn_processed.csv
      - params.yaml
    outs:
      - data/model_data/train_data.parquet.parquet
      - data/model_data/test_data.parquet.parquet

  train:
    cmd: ./venv311/bin/python src/pipeline/model_train.py
    deps:
      - src/pipeline/model_train.py
      - data/model_data/train_data.parquet.parquet
      - params.yaml
    outs:
      - artifacts/random_forest_model

  evaluate:
    cmd: ./venv311/bin/python src/pipeline/eval.py
    deps:
      - src/pipeline/eval.py
      - data/model_data/test_data.parquet.parquet
      - artifacts/random_forest_model
      - params.yaml
    metrics:
      - metrics/model_metrics.json 